// Code generated by Fern. DO NOT EDIT.

package client

import (
	applepay "github.com/square/square-go-sdk/v3/applepay"
	bankaccounts "github.com/square/square-go-sdk/v3/bankaccounts"
	client "github.com/square/square-go-sdk/v3/bookings/client"
	cards "github.com/square/square-go-sdk/v3/cards"
	cashdrawersclient "github.com/square/square-go-sdk/v3/cashdrawers/client"
	catalogclient "github.com/square/square-go-sdk/v3/catalog/client"
	channels "github.com/square/square-go-sdk/v3/channels"
	checkoutclient "github.com/square/square-go-sdk/v3/checkout/client"
	core "github.com/square/square-go-sdk/v3/core"
	customersclient "github.com/square/square-go-sdk/v3/customers/client"
	devicesclient "github.com/square/square-go-sdk/v3/devices/client"
	disputesclient "github.com/square/square-go-sdk/v3/disputes/client"
	employees "github.com/square/square-go-sdk/v3/employees"
	events "github.com/square/square-go-sdk/v3/events"
	giftcardsclient "github.com/square/square-go-sdk/v3/giftcards/client"
	internal "github.com/square/square-go-sdk/v3/internal"
	inventory "github.com/square/square-go-sdk/v3/inventory"
	invoices "github.com/square/square-go-sdk/v3/invoices"
	laborclient "github.com/square/square-go-sdk/v3/labor/client"
	locationsclient "github.com/square/square-go-sdk/v3/locations/client"
	loyaltyclient "github.com/square/square-go-sdk/v3/loyalty/client"
	merchantsclient "github.com/square/square-go-sdk/v3/merchants/client"
	mobile "github.com/square/square-go-sdk/v3/mobile"
	oauth "github.com/square/square-go-sdk/v3/oauth"
	option "github.com/square/square-go-sdk/v3/option"
	ordersclient "github.com/square/square-go-sdk/v3/orders/client"
	payments "github.com/square/square-go-sdk/v3/payments"
	payouts "github.com/square/square-go-sdk/v3/payouts"
	refunds "github.com/square/square-go-sdk/v3/refunds"
	sites "github.com/square/square-go-sdk/v3/sites"
	snippets "github.com/square/square-go-sdk/v3/snippets"
	subscriptions "github.com/square/square-go-sdk/v3/subscriptions"
	team "github.com/square/square-go-sdk/v3/team"
	teammembersclient "github.com/square/square-go-sdk/v3/teammembers/client"
	terminalclient "github.com/square/square-go-sdk/v3/terminal/client"
	transferorders "github.com/square/square-go-sdk/v3/transferorders"
	v1transactions "github.com/square/square-go-sdk/v3/v1transactions"
	vendors "github.com/square/square-go-sdk/v3/vendors"
	webhooksclient "github.com/square/square-go-sdk/v3/webhooks/client"
	os "os"
)

type Client struct {
	OAuth          *oauth.Client
	V1Transactions *v1transactions.Client
	ApplePay       *applepay.Client
	BankAccounts   *bankaccounts.Client
	Bookings       *client.Client
	Cards          *cards.Client
	Catalog        *catalogclient.Client
	Channels       *channels.Client
	Customers      *customersclient.Client
	Devices        *devicesclient.Client
	Disputes       *disputesclient.Client
	Employees      *employees.Client
	Events         *events.Client
	GiftCards      *giftcardsclient.Client
	Inventory      *inventory.Client
	Invoices       *invoices.Client
	Labor          *laborclient.Client
	Locations      *locationsclient.Client
	Loyalty        *loyaltyclient.Client
	Merchants      *merchantsclient.Client
	Checkout       *checkoutclient.Client
	Orders         *ordersclient.Client
	Payments       *payments.Client
	Payouts        *payouts.Client
	Refunds        *refunds.Client
	Sites          *sites.Client
	Snippets       *snippets.Client
	Subscriptions  *subscriptions.Client
	TeamMembers    *teammembersclient.Client
	Team           *team.Client
	Terminal       *terminalclient.Client
	TransferOrders *transferorders.Client
	Vendors        *vendors.Client
	Mobile         *mobile.Client
	CashDrawers    *cashdrawersclient.Client
	Webhooks       *webhooksclient.Client

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(opts ...option.RequestOption) *Client {
	options := core.NewRequestOptions(opts...)
	if options.Token == "" {
		options.Token = os.Getenv("SQUARE_TOKEN")
	}
	if options.Version == "" {
		options.Version = os.Getenv("VERSION")
	}
	return &Client{
		OAuth:          oauth.NewClient(options),
		V1Transactions: v1transactions.NewClient(options),
		ApplePay:       applepay.NewClient(options),
		BankAccounts:   bankaccounts.NewClient(options),
		Bookings:       client.NewClient(options),
		Cards:          cards.NewClient(options),
		Catalog:        catalogclient.NewClient(options),
		Channels:       channels.NewClient(options),
		Customers:      customersclient.NewClient(options),
		Devices:        devicesclient.NewClient(options),
		Disputes:       disputesclient.NewClient(options),
		Employees:      employees.NewClient(options),
		Events:         events.NewClient(options),
		GiftCards:      giftcardsclient.NewClient(options),
		Inventory:      inventory.NewClient(options),
		Invoices:       invoices.NewClient(options),
		Labor:          laborclient.NewClient(options),
		Locations:      locationsclient.NewClient(options),
		Loyalty:        loyaltyclient.NewClient(options),
		Merchants:      merchantsclient.NewClient(options),
		Checkout:       checkoutclient.NewClient(options),
		Orders:         ordersclient.NewClient(options),
		Payments:       payments.NewClient(options),
		Payouts:        payouts.NewClient(options),
		Refunds:        refunds.NewClient(options),
		Sites:          sites.NewClient(options),
		Snippets:       snippets.NewClient(options),
		Subscriptions:  subscriptions.NewClient(options),
		TeamMembers:    teammembersclient.NewClient(options),
		Team:           team.NewClient(options),
		Terminal:       terminalclient.NewClient(options),
		TransferOrders: transferorders.NewClient(options),
		Vendors:        vendors.NewClient(options),
		Mobile:         mobile.NewClient(options),
		CashDrawers:    cashdrawersclient.NewClient(options),
		Webhooks:       webhooksclient.NewClient(options),
		options:        options,
		baseURL:        options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}
