// Code generated by Fern. DO NOT EDIT.

package loyalty_rewards_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	square "github.com/square/square-go-sdk/v3"
	client "github.com/square/square-go-sdk/v3/client"
	loyalty "github.com/square/square-go-sdk/v3/loyalty"
	option "github.com/square/square-go-sdk/v3/option"
	require "github.com/stretchr/testify/require"
	http "net/http"
	os "os"
	testing "testing"
)

func VerifyRequestCount(
	t *testing.T,
	testId string,
	method string,
	urlPath string,
	queryParams map[string]string,
	expected int,
) {
	wiremockURL := os.Getenv("WIREMOCK_URL")
	if wiremockURL == "" {
		wiremockURL = "http://localhost:8080"
	}
	WiremockAdminURL := wiremockURL + "/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
	reqBody.WriteString(testId)
	reqBody.WriteString(`"}}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			reqBody.WriteString(`":{"equalTo":"`)
			reqBody.WriteString(value)
			reqBody.WriteString(`"}`)
			first = false
		}
		reqBody.WriteString("}")
	}
	reqBody.WriteString("}")
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestLoyaltyRewardsCreateWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &loyalty.CreateLoyaltyRewardRequest{
		Reward: &square.LoyaltyReward{
			LoyaltyAccountID: "5adcb100-07f1-4ee7-b8c6-6bb9ebc474bd",
			RewardTierID:     "e1b39225-9da5-43d1-a5db-782cdd8ad94f",
			OrderID: square.String(
				"RFZfrdtm3mhO1oGzf5Cx7fEMsmGZY",
			),
		},
		IdempotencyKey: "18c2e5ea-a620-4b1f-ad60-7b167285e451",
	}
	_, invocationErr := client.Loyalty.Rewards.Create(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestLoyaltyRewardsCreateWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestLoyaltyRewardsCreateWithWireMock", "POST", "/v2/loyalty/rewards", nil, 1)
}

func TestLoyaltyRewardsSearchWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &loyalty.SearchLoyaltyRewardsRequest{
		Query: &square.SearchLoyaltyRewardsRequestLoyaltyRewardQuery{
			LoyaltyAccountID: "5adcb100-07f1-4ee7-b8c6-6bb9ebc474bd",
		},
		Limit: square.Int(
			10,
		),
	}
	_, invocationErr := client.Loyalty.Rewards.Search(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestLoyaltyRewardsSearchWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestLoyaltyRewardsSearchWithWireMock", "POST", "/v2/loyalty/rewards/search", nil, 1)
}

func TestLoyaltyRewardsGetWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &loyalty.GetRewardsRequest{
		RewardID: "reward_id",
	}
	_, invocationErr := client.Loyalty.Rewards.Get(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestLoyaltyRewardsGetWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestLoyaltyRewardsGetWithWireMock", "GET", "/v2/loyalty/rewards/reward_id", nil, 1)
}

func TestLoyaltyRewardsDeleteWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &loyalty.DeleteRewardsRequest{
		RewardID: "reward_id",
	}
	_, invocationErr := client.Loyalty.Rewards.Delete(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestLoyaltyRewardsDeleteWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestLoyaltyRewardsDeleteWithWireMock", "DELETE", "/v2/loyalty/rewards/reward_id", nil, 1)
}

func TestLoyaltyRewardsRedeemWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &loyalty.RedeemLoyaltyRewardRequest{
		RewardID:       "reward_id",
		IdempotencyKey: "98adc7f7-6963-473b-b29c-f3c9cdd7d994",
		LocationID:     "P034NEENMD09F",
	}
	_, invocationErr := client.Loyalty.Rewards.Redeem(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestLoyaltyRewardsRedeemWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestLoyaltyRewardsRedeemWithWireMock", "POST", "/v2/loyalty/rewards/reward_id/redeem", nil, 1)
}
