package orders

// CustomAttributesDeleteRequest is an alias for DeleteCustomAttributesRequest.
type CustomAttributesDeleteRequest = DeleteCustomAttributesRequest

// CustomAttributesGetRequest is an alias for GetCustomAttributesRequest.
type CustomAttributesGetRequest = GetCustomAttributesRequest

// CustomAttributesListRequest is an alias for ListCustomAttributesRequest.
type CustomAttributesListRequest = ListCustomAttributesRequest

type CustomAttributeDefinitionsDeleteRequest = DeleteCustomAttributeDefinitionsRequest

// CustomAttributeDefinitionsGetRequest is an alias for GetCustomAttributeDefinitionsRequest.
type CustomAttributeDefinitionsGetRequest = GetCustomAttributeDefinitionsRequest

// CustomAttributeDefinitionsListRequest is an alias for ListCustomAttributeDefinitionsRequest.
type CustomAttributeDefinitionsListRequest = ListCustomAttributeDefinitionsRequest
