// Code generated by Fern. DO NOT EDIT.

package labor

import (
	v2 "github.com/square/square-go-sdk/v2"
)

type UpdateWorkweekConfigRequest struct {
	// The UUID for the `WorkweekConfig` object being updated.
	ID string `json:"-" url:"-"`
	// The updated `WorkweekConfig` object.
	WorkweekConfig *v2.WorkweekConfig `json:"workweek_config,omitempty" url:"-"`
}

type ListWorkweekConfigsRequest struct {
	// The maximum number of `WorkweekConfigs` results to return per page.
	Limit *int `json:"-" url:"limit,omitempty"`
	// A pointer to the next page of `WorkweekConfig` results to fetch.
	Cursor *string `json:"-" url:"cursor,omitempty"`
}
