// Code generated by Fern. DO NOT EDIT.

package customers_cards_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	square "github.com/square/square-go-sdk/v3"
	client "github.com/square/square-go-sdk/v3/client"
	customers "github.com/square/square-go-sdk/v3/customers"
	option "github.com/square/square-go-sdk/v3/option"
	require "github.com/stretchr/testify/require"
	http "net/http"
	os "os"
	testing "testing"
)

func VerifyRequestCount(
	t *testing.T,
	testId string,
	method string,
	urlPath string,
	queryParams map[string]string,
	expected int,
) {
	wiremockURL := os.Getenv("WIREMOCK_URL")
	if wiremockURL == "" {
		wiremockURL = "http://localhost:8080"
	}
	WiremockAdminURL := wiremockURL + "/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
	reqBody.WriteString(testId)
	reqBody.WriteString(`"}}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			reqBody.WriteString(`":{"equalTo":"`)
			reqBody.WriteString(value)
			reqBody.WriteString(`"}`)
			first = false
		}
		reqBody.WriteString("}")
	}
	reqBody.WriteString("}")
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestCustomersCardsCreateWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &customers.CreateCustomerCardRequest{
		CustomerID: "customer_id",
		CardNonce:  "YOUR_CARD_NONCE",
		BillingAddress: &square.Address{
			AddressLine1: square.String(
				"500 Electric Ave",
			),
			AddressLine2: square.String(
				"Suite 600",
			),
			Locality: square.String(
				"New York",
			),
			AdministrativeDistrictLevel1: square.String(
				"NY",
			),
			PostalCode: square.String(
				"10003",
			),
			Country: square.CountryUs.Ptr(),
		},
		CardholderName: square.String(
			"Amelia Earhart",
		),
	}
	_, invocationErr := client.Customers.Cards.Create(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestCustomersCardsCreateWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestCustomersCardsCreateWithWireMock", "POST", "/v2/customers/customer_id/cards", nil, 1)
}

func TestCustomersCardsDeleteWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &customers.DeleteCardsRequest{
		CustomerID: "customer_id",
		CardID:     "card_id",
	}
	_, invocationErr := client.Customers.Cards.Delete(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestCustomersCardsDeleteWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestCustomersCardsDeleteWithWireMock", "DELETE", "/v2/customers/customer_id/cards/card_id", nil, 1)
}
