// This file was auto-generated by Fern from our API Definition.

package catalog

import (
	squaregosdk "github.com/square/square-go-sdk"
	io "io"
)

type CreateImagesRequest struct {
	ImageFile io.Reader                              `json:"-" url:"-"`
	Request   *squaregosdk.CreateCatalogImageRequest `json:"request,omitempty" url:"-"`
}

type UpdateImagesRequest struct {
	// The ID of the `CatalogImage` object to update the encapsulated image file.
	ImageID   string                                 `json:"-" url:"-"`
	ImageFile io.Reader                              `json:"-" url:"-"`
	Request   *squaregosdk.UpdateCatalogImageRequest `json:"request,omitempty" url:"-"`
}
