// Code generated by Fern. DO NOT EDIT.

package catalog

import (
	json "encoding/json"
	assert "github.com/stretchr/testify/assert"
	require "github.com/stretchr/testify/require"
	testing "testing"
)

func TestSettersDeleteObjectRequest(t *testing.T) {
	t.Run("SetObjectID", func(t *testing.T) {
		obj := &DeleteObjectRequest{}
		var fernTestValueObjectID string
		obj.SetObjectID(fernTestValueObjectID)
		assert.Equal(t, fernTestValueObjectID, obj.ObjectID)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitDeleteObjectRequest(t *testing.T) {
	t.Run("SetObjectID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DeleteObjectRequest{}
		var fernTestValueObjectID string

		// Act
		obj.SetObjectID(fernTestValueObjectID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersGetObjectRequest(t *testing.T) {
	t.Run("SetObjectID", func(t *testing.T) {
		obj := &GetObjectRequest{}
		var fernTestValueObjectID string
		obj.SetObjectID(fernTestValueObjectID)
		assert.Equal(t, fernTestValueObjectID, obj.ObjectID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetIncludeRelatedObjects", func(t *testing.T) {
		obj := &GetObjectRequest{}
		var fernTestValueIncludeRelatedObjects *bool
		obj.SetIncludeRelatedObjects(fernTestValueIncludeRelatedObjects)
		assert.Equal(t, fernTestValueIncludeRelatedObjects, obj.IncludeRelatedObjects)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetCatalogVersion", func(t *testing.T) {
		obj := &GetObjectRequest{}
		var fernTestValueCatalogVersion *int64
		obj.SetCatalogVersion(fernTestValueCatalogVersion)
		assert.Equal(t, fernTestValueCatalogVersion, obj.CatalogVersion)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetIncludeCategoryPathToRoot", func(t *testing.T) {
		obj := &GetObjectRequest{}
		var fernTestValueIncludeCategoryPathToRoot *bool
		obj.SetIncludeCategoryPathToRoot(fernTestValueIncludeCategoryPathToRoot)
		assert.Equal(t, fernTestValueIncludeCategoryPathToRoot, obj.IncludeCategoryPathToRoot)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitGetObjectRequest(t *testing.T) {
	t.Run("SetObjectID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetObjectRequest{}
		var fernTestValueObjectID string

		// Act
		obj.SetObjectID(fernTestValueObjectID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetIncludeRelatedObjects_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetObjectRequest{}
		var fernTestValueIncludeRelatedObjects *bool

		// Act
		obj.SetIncludeRelatedObjects(fernTestValueIncludeRelatedObjects)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetCatalogVersion_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetObjectRequest{}
		var fernTestValueCatalogVersion *int64

		// Act
		obj.SetCatalogVersion(fernTestValueCatalogVersion)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetIncludeCategoryPathToRoot_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetObjectRequest{}
		var fernTestValueIncludeCategoryPathToRoot *bool

		// Act
		obj.SetIncludeCategoryPathToRoot(fernTestValueIncludeCategoryPathToRoot)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersUpsertCatalogObjectRequest(t *testing.T) {
	t.Run("SetIdempotencyKey", func(t *testing.T) {
		obj := &UpsertCatalogObjectRequest{}
		var fernTestValueIdempotencyKey string
		obj.SetIdempotencyKey(fernTestValueIdempotencyKey)
		assert.Equal(t, fernTestValueIdempotencyKey, obj.IdempotencyKey)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitUpsertCatalogObjectRequest(t *testing.T) {
	t.Run("SetIdempotencyKey_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UpsertCatalogObjectRequest{}
		var fernTestValueIdempotencyKey string

		// Act
		obj.SetIdempotencyKey(fernTestValueIdempotencyKey)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}
