// Code generated by Fern. DO NOT EDIT.

package invoices_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	square "github.com/square/square-go-sdk/v3"
	client "github.com/square/square-go-sdk/v3/client"
	option "github.com/square/square-go-sdk/v3/option"
	require "github.com/stretchr/testify/require"
	http "net/http"
	os "os"
	strings "strings"
	testing "testing"
)

func VerifyRequestCount(
	t *testing.T,
	testId string,
	method string,
	urlPath string,
	queryParams map[string]string,
	expected int,
) {
	wiremockURL := os.Getenv("WIREMOCK_URL")
	if wiremockURL == "" {
		wiremockURL = "http://localhost:8080"
	}
	WiremockAdminURL := wiremockURL + "/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
	reqBody.WriteString(testId)
	reqBody.WriteString(`"}}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			reqBody.WriteString(`":{"equalTo":"`)
			reqBody.WriteString(value)
			reqBody.WriteString(`"}`)
			first = false
		}
		reqBody.WriteString("}")
	}
	reqBody.WriteString("}")
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestInvoicesListWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &square.ListInvoicesRequest{
		LocationID: "location_id",
		Cursor: square.String(
			"cursor",
		),
		Limit: square.Int(
			1,
		),
	}
	_, invocationErr := client.Invoices.List(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestInvoicesListWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestInvoicesListWithWireMock", "GET", "/v2/invoices", map[string]string{"location_id": "location_id", "cursor": "cursor", "limit": "1"}, 1)
}

func TestInvoicesCreateWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &square.CreateInvoiceRequest{
		Invoice: &square.Invoice{
			LocationID: square.String(
				"ES0RJRZYEC39A",
			),
			OrderID: square.String(
				"CAISENgvlJ6jLWAzERDzjyHVybY",
			),
			PrimaryRecipient: &square.InvoiceRecipient{
				CustomerID: square.String(
					"JDKYHBWT1D4F8MFH63DBMEN8Y4",
				),
			},
			PaymentRequests: []*square.InvoicePaymentRequest{
				&square.InvoicePaymentRequest{
					RequestType: square.InvoiceRequestTypeBalance.Ptr(),
					DueDate: square.String(
						"2030-01-24",
					),
					TippingEnabled: square.Bool(
						true,
					),
					AutomaticPaymentSource: square.InvoiceAutomaticPaymentSourceNone.Ptr(),
					Reminders: []*square.InvoicePaymentReminder{
						&square.InvoicePaymentReminder{
							RelativeScheduledDays: square.Int(
								-1,
							),
							Message: square.String(
								"Your invoice is due tomorrow",
							),
						},
					},
				},
			},
			DeliveryMethod: square.InvoiceDeliveryMethodEmail.Ptr(),
			InvoiceNumber: square.String(
				"inv-100",
			),
			Title: square.String(
				"Event Planning Services",
			),
			Description: square.String(
				"We appreciate your business!",
			),
			ScheduledAt: square.String(
				"2030-01-13T10:00:00Z",
			),
			AcceptedPaymentMethods: &square.InvoiceAcceptedPaymentMethods{
				Card: square.Bool(
					true,
				),
				SquareGiftCard: square.Bool(
					false,
				),
				BankAccount: square.Bool(
					false,
				),
				BuyNowPayLater: square.Bool(
					false,
				),
				CashAppPay: square.Bool(
					false,
				),
			},
			CustomFields: []*square.InvoiceCustomField{
				&square.InvoiceCustomField{
					Label: square.String(
						"Event Reference Number",
					),
					Value: square.String(
						"Ref. #1234",
					),
					Placement: square.InvoiceCustomFieldPlacementAboveLineItems.Ptr(),
				},
				&square.InvoiceCustomField{
					Label: square.String(
						"Terms of Service",
					),
					Value: square.String(
						"The terms of service are...",
					),
					Placement: square.InvoiceCustomFieldPlacementBelowLineItems.Ptr(),
				},
			},
			SaleOrServiceDate: square.String(
				"2030-01-24",
			),
			StorePaymentMethodEnabled: square.Bool(
				false,
			),
		},
		IdempotencyKey: square.String(
			"ce3748f9-5fc1-4762-aa12-aae5e843f1f4",
		),
	}
	_, invocationErr := client.Invoices.Create(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestInvoicesCreateWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestInvoicesCreateWithWireMock", "POST", "/v2/invoices", nil, 1)
}

func TestInvoicesSearchWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &square.SearchInvoicesRequest{
		Query: &square.InvoiceQuery{
			Filter: &square.InvoiceFilter{
				LocationIDs: []string{
					"ES0RJRZYEC39A",
				},
				CustomerIDs: []string{
					"JDKYHBWT1D4F8MFH63DBMEN8Y4",
				},
			},
			Sort: &square.InvoiceSort{
				Field: square.InvoiceSortField(
					"INVOICE_SORT_DATE",
				),
				Order: square.SortOrderDesc.Ptr(),
			},
		},
		Limit: square.Int(
			100,
		),
	}
	_, invocationErr := client.Invoices.Search(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestInvoicesSearchWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestInvoicesSearchWithWireMock", "POST", "/v2/invoices/search", nil, 1)
}

func TestInvoicesGetWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &square.GetInvoicesRequest{
		InvoiceID: "invoice_id",
	}
	_, invocationErr := client.Invoices.Get(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestInvoicesGetWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestInvoicesGetWithWireMock", "GET", "/v2/invoices/invoice_id", nil, 1)
}

func TestInvoicesUpdateWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &square.UpdateInvoiceRequest{
		InvoiceID: "invoice_id",
		Invoice: &square.Invoice{
			Version: square.Int(
				1,
			),
			PaymentRequests: []*square.InvoicePaymentRequest{
				&square.InvoicePaymentRequest{
					UID: square.String(
						"2da7964f-f3d2-4f43-81e8-5aa220bf3355",
					),
					TippingEnabled: square.Bool(
						false,
					),
				},
			},
		},
		IdempotencyKey: square.String(
			"4ee82288-0910-499e-ab4c-5d0071dad1be",
		),
	}
	_, invocationErr := client.Invoices.Update(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestInvoicesUpdateWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestInvoicesUpdateWithWireMock", "PUT", "/v2/invoices/invoice_id", nil, 1)
}

func TestInvoicesDeleteWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &square.DeleteInvoicesRequest{
		InvoiceID: "invoice_id",
		Version: square.Int(
			1,
		),
	}
	_, invocationErr := client.Invoices.Delete(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestInvoicesDeleteWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestInvoicesDeleteWithWireMock", "DELETE", "/v2/invoices/invoice_id", map[string]string{"version": "1"}, 1)
}

func TestInvoicesCreateInvoiceAttachmentWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &square.CreateInvoiceAttachmentRequest{
		InvoiceID: "invoice_id",
		ImageFile: strings.NewReader(
			"",
		),
	}
	_, invocationErr := client.Invoices.CreateInvoiceAttachment(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestInvoicesCreateInvoiceAttachmentWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestInvoicesCreateInvoiceAttachmentWithWireMock", "POST", "/v2/invoices/invoice_id/attachments", nil, 1)
}

func TestInvoicesDeleteInvoiceAttachmentWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &square.DeleteInvoiceAttachmentRequest{
		InvoiceID:    "invoice_id",
		AttachmentID: "attachment_id",
	}
	_, invocationErr := client.Invoices.DeleteInvoiceAttachment(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestInvoicesDeleteInvoiceAttachmentWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestInvoicesDeleteInvoiceAttachmentWithWireMock", "DELETE", "/v2/invoices/invoice_id/attachments/attachment_id", nil, 1)
}

func TestInvoicesCancelWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &square.CancelInvoiceRequest{
		InvoiceID: "invoice_id",
		Version:   0,
	}
	_, invocationErr := client.Invoices.Cancel(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestInvoicesCancelWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestInvoicesCancelWithWireMock", "POST", "/v2/invoices/invoice_id/cancel", nil, 1)
}

func TestInvoicesPublishWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &square.PublishInvoiceRequest{
		InvoiceID: "invoice_id",
		Version:   1,
		IdempotencyKey: square.String(
			"32da42d0-1997-41b0-826b-f09464fc2c2e",
		),
	}
	_, invocationErr := client.Invoices.Publish(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestInvoicesPublishWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestInvoicesPublishWithWireMock", "POST", "/v2/invoices/invoice_id/publish", nil, 1)
}
