// This file was auto-generated by Fern from our API Definition.

package client

import (
	core "github.com/square/square-go-sdk/core"
	internal "github.com/square/square-go-sdk/internal"
	breaktypes "github.com/square/square-go-sdk/labor/breaktypes"
	employeewages "github.com/square/square-go-sdk/labor/employeewages"
	shifts "github.com/square/square-go-sdk/labor/shifts"
	teammemberwages "github.com/square/square-go-sdk/labor/teammemberwages"
	workweekconfigs "github.com/square/square-go-sdk/labor/workweekconfigs"
	option "github.com/square/square-go-sdk/option"
	http "net/http"
	os "os"
)

type Client struct {
	baseURL string
	caller  *internal.Caller
	header  http.Header

	BreakTypes      *breaktypes.Client
	EmployeeWages   *employeewages.Client
	Shifts          *shifts.Client
	TeamMemberWages *teammemberwages.Client
	WorkweekConfigs *workweekconfigs.Client
}

func NewClient(opts ...option.RequestOption) *Client {
	options := core.NewRequestOptions(opts...)
	if options.Token == "" {
		options.Token = os.Getenv("SQUARE_TOKEN")
	}
	if options.Version == "" {
		options.Version = os.Getenv("VERSION")
	}
	return &Client{
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
		header:          options.ToHeader(),
		BreakTypes:      breaktypes.NewClient(opts...),
		EmployeeWages:   employeewages.NewClient(opts...),
		Shifts:          shifts.NewClient(opts...),
		TeamMemberWages: teammemberwages.NewClient(opts...),
		WorkweekConfigs: workweekconfigs.NewClient(opts...),
	}
}
