name: ci

on: [push]

jobs:
  integration:
    env:
      TEST_SQUARE_TOKEN: ${{ secrets.TEST_SQUARE_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up go
        uses: actions/setup-go@v4

      - name: Test
        run: go test ./... # TODO: Add the following flag when TEST_SQUARE_TOKEN is configured -- -tags=integration
